// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../../components/HelloWorld.vue')['default']
    InformationCircleIconOutline: typeof import('@heroicons/vue/outline/esm/InformationCircleIcon.js')['default']
  }
}

export { }
